### ISSUE TITLE
百词斩中考英语2124词

### ISSUE THREAD

**Issue by y2012f** [tyza66/BaiCiZhanRememberedToExcel#2]
大佬你好，请问这个能否完整导出百词斩中考英语的2124词呢？由于没有安卓设备，没法尝试，能麻烦您导出一下这2124词的Excel么？

**Comment by tyza66** [comment]
目前能导出的是已背单词里面的所有单词，具体那种成套的英语单词表是咋存的当时没细致研究过，如果有可以用的导出规律的话可以改一下代码就行应该

**Comment by y2012f** [comment]
> 目前能导出的是已背单词里面的所有单词，具体那种成套的英语单词表是咋存的当时没细致研究过，如果有可以用的导出规律的话可以改一下代码就行应该

好的，谢谢
